package studio

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"

	"codeburg.org/lexbit/lurpicui/cmd/lurpiclint/capabilities"
	"codeburg.org/lexbit/lurpicui/demos/lurpic_studio/state"
	"codeburg.org/lexbit/lurpicui/facet"
	"codeburg.org/lexbit/lurpicui/gfx"
	"codeburg.org/lexbit/lurpicui/marks/structure"
)

// CapabilityIndex is the read-only Capability Index exhibit. It renders the
// demo's own mark/layout/layer catalog — generated at runtime by the same
// capability-index generator that `lurpiclint capabilities` uses — through the
// framework structure.table mark (FR-14, F-capindex-internal resolution: the
// public `capabilities` seam is the single scan path for both the CLI and the
// demo). The catalog's provenance line is the table's first row and the totals
// line its last, so both are reachable by scrolling the table; the table's
// FR-7 row virtualization keeps only the visible rows built. It is
// documentary, not a coverage contributor.
//
// The scan is cached per-process: the AST walk happens once; later builds
// reuse the catalog. A failed scan is surfaced honestly as a note rather than
// a hand-maintained list (R-fake-viz).
type CapabilityIndex struct {
	facet.Facet
	layout facet.LayoutRole

	table *structure.Table
}

// CapabilityIndexData is the exhibit descriptor for the catalog view.
type CapabilityIndexData struct{}

func NewCapabilityIndexData() *CapabilityIndexData { return &CapabilityIndexData{} }
func (d *CapabilityIndexData) ID() ExhibitID       { return ExhibitCapabilities }
func (d *CapabilityIndexData) Title() string       { return "Capability Index" }
func (d *CapabilityIndexData) Build(_ *state.AppState) facet.FacetImpl {
	return NewCapabilityIndexFacet()
}

// capCatalogOnce caches the module-wide AST scan per process.
var (
	capCatalogOnce sync.Once
	capCatalog     []capabilities.Capability
	capCatalogErr  error
)

// loadCapabilities scans the module surface through the public seam, cached.
func loadCapabilities() ([]capabilities.Capability, error) {
	capCatalogOnce.Do(func() {
		root := findStudioModuleRoot()
		if root == "" {
			capCatalogErr = fmt.Errorf("no go.mod found (source tree unavailable)")
			return
		}
		caps, err := capabilities.Scan(root)
		if err != nil {
			capCatalogErr = err
			return
		}
		capCatalog = caps
	})
	return capCatalog, capCatalogErr
}

// findStudioModuleRoot walks the working directory up for go.mod, mirroring
// lurpiclint's own findModuleRoot so the demo scans exactly the same module.
func findStudioModuleRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		return ""
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}

// capabilityGroup is one concept group of the catalog.
type capabilityGroup struct {
	title string
	caps  []capabilities.Capability //lurpiclint:ignore LL012 -- cached read-only catalog rows, not interactive domain state (F-lint-hosts)
}

// NewCapabilityIndexFacet builds the read-only catalog view over a single
// structure.table mark.
func NewCapabilityIndexFacet() *CapabilityIndex {
	e := &CapabilityIndex{}
	e.Facet = facet.NewFacet()

	caps, err := loadCapabilities()
	if err != nil {
		// R-fake-viz: never fabricate the catalog; surface the honest note.
		e.table = structure.NewTable("Capability catalog", capabilityNoteTable("The Capability Index could not be generated.", err.Error()), nil)
		buildIndexHost(e)
		return e
	}

	e.table = structure.NewTable("Capability catalog", capabilityTableData(caps), nil)
	buildIndexHost(e)
	return e
}

// capabilityTableData builds the catalog table snapshot: a provenance row, one
// section-header row per concept group followed by its rows, and a totals row
// (FR-14 — "322 (+3 section headers +2 text lines)").
func capabilityTableData(caps []capabilities.Capability) structure.TableData {
	columns := []structure.TableColumn{
		{Key: "kind", Label: "Kind"},
		{Key: "path", Label: "Path"},
		{Key: "intent", Label: "Intent", Width: 360},
	}
	rows := make([]structure.TableRow, 0, len(caps)+5)
	rows = append(rows, structure.TableRow{
		Key:   "note:provenance",
		Cells: []string{"", "generated by the capindex generator — the same scan projectile `lurpiclint capabilities` uses", ""},
	})
	for _, g := range splitCapabilityGroups(caps) {
		rows = append(rows, structure.TableRow{
			Key:   "section:" + g.title,
			Cells: []string{fmt.Sprintf("%s (%d)", g.title, len(g.caps)), "", ""},
		})
		for i, c := range g.caps {
			rows = append(rows, structure.TableRow{
				Key:   "cap:" + c.Path + ":" + fmt.Sprint(i),
				Cells: []string{c.Kind.String(), c.Path, capabilityIntent(c)},
			})
		}
	}
	sum := capTotals(caps)
	rows = append(rows, structure.TableRow{
		Key:   "note:totals",
		Cells: []string{"", fmt.Sprintf("%d marks · %d layouts · %d layers", sum[capabilities.KindMark], sum[capabilities.KindLayout], sum[capabilities.KindLayer]), ""},
	})
	return structure.TableData{Columns: columns, Rows: rows}
}

// capabilityNoteTable is the honest fallback snapshot when the catalog scan
// failed: a single note row carrying the reason.
func capabilityNoteTable(head, detail string) structure.TableData {
	return structure.TableData{
		Columns: []structure.TableColumn{
			{Key: "kind", Label: "Kind"},
			{Key: "path", Label: "Path"},
			{Key: "intent", Label: "Intent", Width: 360},
		},
		Rows: []structure.TableRow{
			{Key: "note:error", Cells: []string{"", head, detail}},
		},
	}
}

// capabilityIntent extracts the capability's intent (first sentence), truncated
// so the read-only table stays compact.
func capabilityIntent(c capabilities.Capability) string {
	intent := strings.TrimSpace(c.Intent)
	if len(intent) > 80 {
		intent = intent[:77] + "…"
	}
	return intent
}

// capTotals counts the catalog entries per kind.
func capTotals(caps []capabilities.Capability) map[capabilities.CapabilityKind]int {
	out := make(map[capabilities.CapabilityKind]int)
	for _, c := range caps {
		out[c.Kind]++
	}
	return out
}

// splitCapabilityGroups groups the catalog by kind, sorted by path.
func splitCapabilityGroups(caps []capabilities.Capability) []*capabilityGroup {
	grouped := make(map[capabilities.CapabilityKind][]capabilities.Capability)
	for _, c := range caps {
		grouped[c.Kind] = append(grouped[c.Kind], c)
	}
	order := []struct {
		kind  capabilities.CapabilityKind
		title string
	}{
		{capabilities.KindMark, "Marks"},
		{capabilities.KindLayout, "Layouts"},
		{capabilities.KindLayer, "Layers"},
	}
	out := make([]*capabilityGroup, 0, len(order))
	for _, o := range order {
		list := grouped[o.kind]
		sort.Slice(list, func(i, j int) bool { return list[i].Path < list[j].Path })
		out = append(out, &capabilityGroup{title: o.title, caps: list})
	}
	return out
}

func buildIndexHost(e *CapabilityIndex) {
	e.Facet = facet.NewFacet()
	e.AddChild(e.table.Base())
	e.layout = facet.LayoutRole{ //lurpiclint:ignore * -- bespoke exhibit host (F-lint-hosts)
		OnMeasure: func(ctx facet.MeasureContext, c facet.Constraints) facet.MeasureResult {
			if role := e.table.Base().LayoutRole(); role != nil {
				role.Measure(ctx, facet.Constraints{MaxSize: c.MaxSize})
			}
			return facet.MeasureResult{Size: c.Constrain(c.MaxSize)}
		},
		OnArrange: func(ctx facet.ArrangeContext, bounds gfx.Rect) {
			if role := e.table.Base().LayoutRole(); role != nil {
				role.Arrange(ctx, bounds)
			}
		},
	}
	e.layout.Child = linearChildContract(facet.StretchPolicy{Width: facet.StretchAlways, Height: facet.StretchAlways})
	e.AddRole(&e.layout)
}

func (e *CapabilityIndex) Base() *facet.Facet             { e.BindImpl(e); return &e.Facet }
func (e *CapabilityIndex) OnAttach(_ facet.AttachContext) {}
func (e *CapabilityIndex) OnDetach()                      {}
func (e *CapabilityIndex) OnActivate()                    {}
func (e *CapabilityIndex) OnDeactivate()                  {}

// Table returns the catalog table mark.
func (e *CapabilityIndex) Table() *structure.Table { return e.table }
