package studio

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"

	"codeburg.org/lexbit/lurpicui/cmd/lurpiclint/capabilities"
	"codeburg.org/lexbit/lurpicui/demos/lurpic_studio/state"
	"codeburg.org/lexbit/lurpicui/facet"
	"codeburg.org/lexbit/lurpicui/gfx"
	"codeburg.org/lexbit/lurpicui/marks"
	"codeburg.org/lexbit/lurpicui/marks/primitive"
	"codeburg.org/lexbit/lurpicui/marks/structure"
)

// CapabilityIndex is the read-only Capability Index exhibit. It displays the
// demo's own mark/layout/layer catalog generated at runtime by the same
// capability-index generator that `lurpiclint capabilities` uses (FR-capindex,
// F-capindex-internal resolution: the public `capabilities` seam is the single
// scan path for both the CLI and the demo). It is documentary, not a coverage
// contributor.
//
// The scan is cached per-process: the AST walk happens once; later builds
// reuse the catalog. A failed scan is surfaced honestly as a note rather than
// a hand-maintained list (R-fake-viz).
type CapabilityIndex struct {
	facet.Facet
	layout facet.LayoutRole

	scroll *structure.ScrollRegion
}

// CapabilityIndexData is the exhibit descriptor for the catalog view.
type CapabilityIndexData struct{}

func NewCapabilityIndexData() *CapabilityIndexData { return &CapabilityIndexData{} }
func (d *CapabilityIndexData) ID() ExhibitID       { return ExhibitCapabilities }
func (d *CapabilityIndexData) Title() string       { return "Capability Index" }
func (d *CapabilityIndexData) Build(_ *state.AppState) facet.FacetImpl {
	return NewCapabilityIndexFacet()
}

// capCatalogOnce caches the module-wide AST scan per process.
var (
	capCatalogOnce sync.Once
	capCatalog     []capabilities.Capability
	capCatalogErr  error
)

// loadCapabilities scans the module surface through the public seam, cached.
func loadCapabilities() ([]capabilities.Capability, error) {
	capCatalogOnce.Do(func() {
		root := findStudioModuleRoot()
		if root == "" {
			capCatalogErr = fmt.Errorf("no go.mod found (source tree unavailable)")
			return
		}
		caps, err := capabilities.Scan(root)
		if err != nil {
			capCatalogErr = err
			return
		}
		capCatalog = caps
	})
	return capCatalog, capCatalogErr
}

// findStudioModuleRoot walks the working directory up for go.mod, mirroring
// lurpiclint's own findModuleRoot so the demo scans exactly the same module.
func findStudioModuleRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		return ""
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}

// capabilityGroup is one grouped card of the catalog.
type capabilityGroup struct {
	title string
	caps  []capabilities.Capability //lurpiclint:ignore LL012 -- cached read-only catalog rows, not interactive domain state (F-lint-hosts)
	card  *structure.Card
}

// NewCapabilityIndexFacet builds the read-only catalog view.
func NewCapabilityIndexFacet() *CapabilityIndex {
	e := &CapabilityIndex{}
	e.Facet = facet.NewFacet()
	e.scroll = structure.NewScrollRegion("Capability catalog")

	caps, err := loadCapabilities()
	if err != nil {
		// R-fake-viz: never fabricate the catalog; surface the honest note.
		note := primitive.NewText(marks.Const("Capability catalog unavailable: " + err.Error()))
		e.scroll.SetChildren([]structure.ScrollRegionChild{
			catalogChild(primitive.NewText(marks.Const("The Capability Index could not be generated.")), 0),
			catalogChild(note, 1),
		})
		buildIndexHost(e)
		return e
	}

	e.scroll.SetChildren(catalogChildren(caps))
	buildIndexHost(e)
	return e
}

// catalogChildren builds the scroll content: a provenance line, a card per
// capability group, and a totals line.
func catalogChildren(caps []capabilities.Capability) []structure.ScrollRegionChild {
	groups := splitCapabilityGroups(caps)
	body := make([]structure.ScrollRegionChild, 0, len(groups)+2)
	body = append(body, catalogChild(
		primitive.NewText(marks.Const("generated by the capindex generator — the same scan projectile `lurpiclint capabilities` uses")),
		0,
	))
	for i, g := range groups {
		body = append(body, catalogChild(g.card, i+1))
	}
	sum := capTotals(caps)
	body = append(body, catalogChild(primitive.NewText(marks.Const(fmt.Sprintf(
		"%d marks · %d layouts · %d layers", sum[capabilities.KindMark], sum[capabilities.KindLayout], sum[capabilities.KindLayer]))), len(groups)+1))
	return body
}

// capTotals counts the catalog entries per kind.
func capTotals(caps []capabilities.Capability) map[capabilities.CapabilityKind]int {
	out := make(map[capabilities.CapabilityKind]int)
	for _, c := range caps {
		out[c.Kind]++
	}
	return out
}

// splitCapabilityGroups groups the catalog by kind, sorted by path.
func splitCapabilityGroups(caps []capabilities.Capability) []*capabilityGroup {
	grouped := make(map[capabilities.CapabilityKind][]capabilities.Capability)
	for _, c := range caps {
		grouped[c.Kind] = append(grouped[c.Kind], c)
	}
	order := []struct {
		kind  capabilities.CapabilityKind
		title string
	}{
		{capabilities.KindMark, "Marks"},
		{capabilities.KindLayout, "Layouts"},
		{capabilities.KindLayer, "Layers"},
	}
	out := make([]*capabilityGroup, 0, len(order))
	for _, o := range order {
		list := grouped[o.kind]
		sort.Slice(list, func(i, j int) bool { return list[i].Path < list[j].Path })
		g := &capabilityGroup{title: o.title, caps: list}
		g.card = capabilityCard(g)
		out = append(out, g)
	}
	return out
}

// capabilityCard builds the card of catalog rows: one text row per capability.
func capabilityCard(g *capabilityGroup) *structure.Card {
	c := structure.NewCard(fmt.Sprintf("%s (%d)", g.title, len(g.caps)))
	c.GridColumns = marks.Const(1)
	c.GridRows = marks.Const(len(g.caps) + 1)
	for i, cap := range g.caps {
		c.ChildrenContent = append(c.ChildrenContent, structure.CardChild{
			Key:   g.title + fmt.Sprint(i),
			Facet: primitive.NewText(marks.Const(capabilityRow(cap))),
			Grid:  facet.GridPlacement{ColStart: 0, RowStart: i + 1, ColSpan: 1, RowSpan: 1},
		})
	}
	return c
}

// capabilityRow formats one catalog entry: path — intent (first sentence).
func capabilityRow(c capabilities.Capability) string {
	intent := strings.TrimSpace(c.Intent)
	if len(intent) > 80 {
		intent = intent[:77] + "…"
	}
	if intent == "" {
		return c.Path
	}
	return c.Path + " — " + intent
}

func buildIndexHost(e *CapabilityIndex) {
	e.Facet = facet.NewFacet()
	e.AddChild(e.scroll.Base())
	e.layout = facet.LayoutRole{ //lurpiclint:ignore * -- bespoke exhibit host (F-lint-hosts)
		OnMeasure: func(ctx facet.MeasureContext, c facet.Constraints) facet.MeasureResult {
			if role := e.scroll.Base().LayoutRole(); role != nil {
				role.Measure(ctx, facet.Constraints{MaxSize: c.MaxSize})
			}
			return facet.MeasureResult{Size: c.Constrain(c.MaxSize)}
		},
		OnArrange: func(ctx facet.ArrangeContext, bounds gfx.Rect) {
			if role := e.scroll.Base().LayoutRole(); role != nil {
				role.Arrange(ctx, bounds)
			}
		},
	}
	e.layout.Child = linearChildContract(facet.StretchPolicy{Width: facet.StretchAlways, Height: facet.StretchAlways})
	e.AddRole(&e.layout)
}

func catalogChild(facet facet.FacetImpl, order int) structure.ScrollRegionChild {
	return structure.ScrollRegionChild{
		Facet:     facet,
		Placement: linearPlacement(order),
	}
}

func linearPlacement(order int) facet.Placement {
	return facet.Placement{
		Mode:   facet.PlacementLinear,
		Linear: facet.LinearPlacement{Order: order, CrossAxisAlign: facet.CrossAxisStretch},
	}
}

func (e *CapabilityIndex) Base() *facet.Facet             { e.BindImpl(e); return &e.Facet }
func (e *CapabilityIndex) OnAttach(_ facet.AttachContext) {}
func (e *CapabilityIndex) OnDetach()                      {}
func (e *CapabilityIndex) OnActivate()                    {}
func (e *CapabilityIndex) OnDeactivate()                  {}

// CapabilityCards returns the grouped cards for tests.
func (e *CapabilityIndex) Scroll() *structure.ScrollRegion { return e.scroll }
