package studio

// The gallery's exhibit catalog — the single source of the exhibit list that
// the index pane (nav_rail + tree_navigator), the narrow tree's nav_drawer and
// bottom rail, the command palette, and the status bar caption all share.
// Concept groups drive the tree_navigator's grouping; icons drive the
// nav_rail / nav_drawer destinations.

// exhibitEntry describes one gallery exhibit.
type exhibitEntry struct {
	id    ExhibitID
	title string
	group string
	desc  string
	icon  string
}

// Concept-group labels shared by the catalog, the index tree, the narrow
// drawer sections, and the command palette categories.
const (
	exhibitGroupCatalog  = "Catalog"
	exhibitGroupRealtime = "Realtime"
	exhibitGroupShell    = "Shell"
)

// exhibitCatalog is the gallery's ordered exhibit list.
var exhibitCatalog = []exhibitEntry{
	{ExhibitCapabilities, "Capability Index", exhibitGroupCatalog, "The framework's mark/layout/layer catalog, generated by the same scan lurpiclint capabilities uses.", iconCapabilities},
	{ExhibitRealtime, "Realtime Data", exhibitGroupRealtime, "Streaming chart + editable spreadsheet: a tick, a cell edit, a pan/zoom and a brush each re-project the canvas alone.", iconRealtime},
	{ExhibitLayers, "Layers & Hit Routing", exhibitGroupShell, "The frozen layer registry live: a modal scrim blocks below, a tooltip passes through, paint order is observable.", iconLayers},
	{ExhibitAnchors, "Anchored Overlays", exhibitGroupShell, "Popovers anchored to a draggable trigger re-resolve on move and resize via the layer anchor recipe.", iconAnchors},
	{ExhibitPolicies, "Layout Policies", exhibitGroupShell, "The layout/split policy redistributing live as panes are added, removed, and toggled flex/fixed.", iconPolicies},
	{ExhibitPropagation, "Reactive Propagation", exhibitGroupShell, "The runtime's per-frame dirty wave with per-facet invalidation sources, fed by the DirtySnapshotSink.", iconPropagation},
	{ExhibitPlayground, "Mark Playground", exhibitGroupCatalog, "The action/input/selection/navigation/feedback/status families, each mark interactive with a store write-back loop.", iconPlayground},
}

// exhibitIndex returns the catalog position of an exhibit (-1 when absent).
func exhibitIndex(id ExhibitID) int {
	for i, e := range exhibitCatalog {
		if e.id == id {
			return i
		}
	}
	return -1
}

// exhibitTitle returns the display title for an exhibit id.
func exhibitTitle(id ExhibitID) string {
	for _, e := range exhibitCatalog {
		if e.id == id {
			return e.title
		}
	}
	return string(id)
}

// exhibitDescription returns the one-line description for an exhibit id.
func exhibitDescription(id ExhibitID) string {
	for _, e := range exhibitCatalog {
		if e.id == id {
			return e.desc
		}
	}
	return ""
}

// Simple inline SVG glyphs for the nav_rail / nav_drawer destinations. They
// render deterministically without the asset manager (matching the marks' own
// golden tests).
const (
	iconCapabilities = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M4 4h16M4 12h16M4 20h10"/></svg>`
	iconRealtime     = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M3 17l5-6 4 4 6-8"/><path d="M15 7h4v4"/></svg>`
	iconLayers       = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M12 3l9 5-9 5-9-5z"/><path d="M3 12l9 5 9-5"/></svg>`
	iconAnchors      = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3"/></svg>`
	iconPolicies     = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M4 6h16M4 12h16M4 18h16"/><path d="M9 6v12"/></svg>`
	iconPropagation  = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><circle cx="5" cy="6" r="2"/><circle cx="19" cy="6" r="2"/><circle cx="12" cy="18" r="2"/><path d="M7 7l4 9M17 7l-4 9"/></svg>`
	iconPlayground   = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18M9 21V9"/></svg>`

	// Chart-type glyphs for the E1 radial reshape dial.
	iconChartLine  = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M3 17l5-6 4 4 6-8"/></svg>`
	iconChartArea  = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M3 17l5-6 4 4 6-8"/><path d="M3 17h18"/></svg>`
	iconChartPoint = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><circle cx="8" cy="11" r="2"/><circle cx="16" cy="13" r="2"/><path d="M3 17l5-6 4 4 6-8"/></svg>`
	iconChartBar   = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M4 20V12M10 20V6M16 20V10M22 20V4"/></svg>`

	// Jump-to-live glyph for the E1 live-tail resume control.
	iconJumpLive = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M13 17l5-5-5-5"/><path d="M6 17l5-5-5-5"/><path d="M6 6h12"/></svg>`
)
