// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cfnt

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FontMetrics struct {
	_tab flatbuffers.Table
}

func GetRootAsFontMetrics(buf []byte, offset flatbuffers.UOffsetT) *FontMetrics {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FontMetrics{}
	x.Init(buf, n+offset)
	return x
}

func FinishFontMetricsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFontMetrics(buf []byte, offset flatbuffers.UOffsetT) *FontMetrics {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FontMetrics{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFontMetricsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FontMetrics) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FontMetrics) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FontMetrics) UnitsPerEm() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FontMetrics) MutateUnitsPerEm(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *FontMetrics) Ascent() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *FontMetrics) MutateAscent(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *FontMetrics) Descent() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *FontMetrics) MutateDescent(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *FontMetrics) LineGap() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *FontMetrics) MutateLineGap(n float32) bool {
	return rcv._tab.MutateFloat32Slot(10, n)
}

func (rcv *FontMetrics) CapHeight() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *FontMetrics) MutateCapHeight(n float32) bool {
	return rcv._tab.MutateFloat32Slot(12, n)
}

func (rcv *FontMetrics) XHeight() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *FontMetrics) MutateXHeight(n float32) bool {
	return rcv._tab.MutateFloat32Slot(14, n)
}

func FontMetricsStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func FontMetricsAddUnitsPerEm(builder *flatbuffers.Builder, unitsPerEm uint16) {
	builder.PrependUint16Slot(0, unitsPerEm, 0)
}
func FontMetricsAddAscent(builder *flatbuffers.Builder, ascent float32) {
	builder.PrependFloat32Slot(1, ascent, 0.0)
}
func FontMetricsAddDescent(builder *flatbuffers.Builder, descent float32) {
	builder.PrependFloat32Slot(2, descent, 0.0)
}
func FontMetricsAddLineGap(builder *flatbuffers.Builder, lineGap float32) {
	builder.PrependFloat32Slot(3, lineGap, 0.0)
}
func FontMetricsAddCapHeight(builder *flatbuffers.Builder, capHeight float32) {
	builder.PrependFloat32Slot(4, capHeight, 0.0)
}
func FontMetricsAddXHeight(builder *flatbuffers.Builder, xHeight float32) {
	builder.PrependFloat32Slot(5, xHeight, 0.0)
}
func FontMetricsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
