// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cfnt

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GlyphMetric struct {
	_tab flatbuffers.Table
}

func GetRootAsGlyphMetric(buf []byte, offset flatbuffers.UOffsetT) *GlyphMetric {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GlyphMetric{}
	x.Init(buf, n+offset)
	return x
}

func FinishGlyphMetricBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGlyphMetric(buf []byte, offset flatbuffers.UOffsetT) *GlyphMetric {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GlyphMetric{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGlyphMetricBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GlyphMetric) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GlyphMetric) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GlyphMetric) Codepoint() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GlyphMetric) MutateCodepoint(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *GlyphMetric) GlyphId() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GlyphMetric) MutateGlyphId(n uint16) bool {
	return rcv._tab.MutateUint16Slot(6, n)
}

func (rcv *GlyphMetric) AdvanceWidth() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *GlyphMetric) MutateAdvanceWidth(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *GlyphMetric) Lsb() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *GlyphMetric) MutateLsb(n float32) bool {
	return rcv._tab.MutateFloat32Slot(10, n)
}

func (rcv *GlyphMetric) BoundsXmin() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *GlyphMetric) MutateBoundsXmin(n float32) bool {
	return rcv._tab.MutateFloat32Slot(12, n)
}

func (rcv *GlyphMetric) BoundsYmin() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *GlyphMetric) MutateBoundsYmin(n float32) bool {
	return rcv._tab.MutateFloat32Slot(14, n)
}

func (rcv *GlyphMetric) BoundsXmax() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *GlyphMetric) MutateBoundsXmax(n float32) bool {
	return rcv._tab.MutateFloat32Slot(16, n)
}

func (rcv *GlyphMetric) BoundsYmax() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *GlyphMetric) MutateBoundsYmax(n float32) bool {
	return rcv._tab.MutateFloat32Slot(18, n)
}

func GlyphMetricStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func GlyphMetricAddCodepoint(builder *flatbuffers.Builder, codepoint uint32) {
	builder.PrependUint32Slot(0, codepoint, 0)
}
func GlyphMetricAddGlyphId(builder *flatbuffers.Builder, glyphId uint16) {
	builder.PrependUint16Slot(1, glyphId, 0)
}
func GlyphMetricAddAdvanceWidth(builder *flatbuffers.Builder, advanceWidth float32) {
	builder.PrependFloat32Slot(2, advanceWidth, 0.0)
}
func GlyphMetricAddLsb(builder *flatbuffers.Builder, lsb float32) {
	builder.PrependFloat32Slot(3, lsb, 0.0)
}
func GlyphMetricAddBoundsXmin(builder *flatbuffers.Builder, boundsXmin float32) {
	builder.PrependFloat32Slot(4, boundsXmin, 0.0)
}
func GlyphMetricAddBoundsYmin(builder *flatbuffers.Builder, boundsYmin float32) {
	builder.PrependFloat32Slot(5, boundsYmin, 0.0)
}
func GlyphMetricAddBoundsXmax(builder *flatbuffers.Builder, boundsXmax float32) {
	builder.PrependFloat32Slot(6, boundsXmax, 0.0)
}
func GlyphMetricAddBoundsYmax(builder *flatbuffers.Builder, boundsYmax float32) {
	builder.PrependFloat32Slot(7, boundsYmax, 0.0)
}
func GlyphMetricEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
