// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cfnt

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type KernPair struct {
	_tab flatbuffers.Table
}

func GetRootAsKernPair(buf []byte, offset flatbuffers.UOffsetT) *KernPair {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KernPair{}
	x.Init(buf, n+offset)
	return x
}

func FinishKernPairBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsKernPair(buf []byte, offset flatbuffers.UOffsetT) *KernPair {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &KernPair{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedKernPairBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *KernPair) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KernPair) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *KernPair) Left() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *KernPair) MutateLeft(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *KernPair) Right() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *KernPair) MutateRight(n uint16) bool {
	return rcv._tab.MutateUint16Slot(6, n)
}

func (rcv *KernPair) Kern() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *KernPair) MutateKern(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func KernPairStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func KernPairAddLeft(builder *flatbuffers.Builder, left uint16) {
	builder.PrependUint16Slot(0, left, 0)
}
func KernPairAddRight(builder *flatbuffers.Builder, right uint16) {
	builder.PrependUint16Slot(1, right, 0)
}
func KernPairAddKern(builder *flatbuffers.Builder, kern float32) {
	builder.PrependFloat32Slot(2, kern, 0.0)
}
func KernPairEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
