// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package csg

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Document struct {
	_tab flatbuffers.Table
}

func GetRootAsDocument(buf []byte, offset flatbuffers.UOffsetT) *Document {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Document{}
	x.Init(buf, n+offset)
	return x
}

func FinishDocumentBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDocument(buf []byte, offset flatbuffers.UOffsetT) *Document {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Document{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDocumentBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Document) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Document) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Document) Bounds(obj *Rect) *Rect {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Rect)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Document) Shapes(obj *Shape, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Document) ShapesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func DocumentStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func DocumentAddBounds(builder *flatbuffers.Builder, bounds flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(bounds), 0)
}
func DocumentAddShapes(builder *flatbuffers.Builder, shapes flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(shapes), 0)
}
func DocumentStartShapesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DocumentEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
