// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package csg

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Rect struct {
	_tab flatbuffers.Struct
}

func (rcv *Rect) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Rect) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Rect) Min(obj *Vec2) *Vec2 {
	if obj == nil {
		obj = new(Vec2)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+0)
	return obj
}
func (rcv *Rect) Max(obj *Vec2) *Vec2 {
	if obj == nil {
		obj = new(Vec2)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+8)
	return obj
}

func CreateRect(builder *flatbuffers.Builder, min_x float32, min_y float32, max_x float32, max_y float32) flatbuffers.UOffsetT {
	builder.Prep(4, 16)
	builder.Prep(4, 8)
	builder.PrependFloat32(max_y)
	builder.PrependFloat32(max_x)
	builder.Prep(4, 8)
	builder.PrependFloat32(min_y)
	builder.PrependFloat32(min_x)
	return builder.Offset()
}
