// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package csg

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Shape struct {
	_tab flatbuffers.Table
}

func GetRootAsShape(buf []byte, offset flatbuffers.UOffsetT) *Shape {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Shape{}
	x.Init(buf, n+offset)
	return x
}

func FinishShapeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsShape(buf []byte, offset flatbuffers.UOffsetT) *Shape {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Shape{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedShapeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Shape) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Shape) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Shape) Fill() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Shape) MutateFill(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *Shape) Stroke() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Shape) MutateStroke(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *Shape) StrokeWidth() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Shape) MutateStrokeWidth(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *Shape) Verbs(j int) Verb {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return Verb(rcv._tab.GetInt8(a + flatbuffers.UOffsetT(j*1)))
	}
	return 0
}

func (rcv *Shape) VerbsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Shape) MutateVerbs(j int, n Verb) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt8(a+flatbuffers.UOffsetT(j*1), int8(n))
	}
	return false
}

func (rcv *Shape) Coords(j int) float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetFloat32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *Shape) CoordsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Shape) MutateCoords(j int, n float32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateFloat32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func (rcv *Shape) Bounds(obj *Rect) *Rect {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Rect)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ShapeStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func ShapeAddFill(builder *flatbuffers.Builder, fill uint32) {
	builder.PrependUint32Slot(0, fill, 0)
}
func ShapeAddStroke(builder *flatbuffers.Builder, stroke uint32) {
	builder.PrependUint32Slot(1, stroke, 0)
}
func ShapeAddStrokeWidth(builder *flatbuffers.Builder, strokeWidth float32) {
	builder.PrependFloat32Slot(2, strokeWidth, 0.0)
}
func ShapeAddVerbs(builder *flatbuffers.Builder, verbs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(verbs), 0)
}
func ShapeStartVerbsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ShapeAddCoords(builder *flatbuffers.Builder, coords flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(coords), 0)
}
func ShapeStartCoordsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ShapeAddBounds(builder *flatbuffers.Builder, bounds flatbuffers.UOffsetT) {
	builder.PrependStructSlot(5, flatbuffers.UOffsetT(bounds), 0)
}
func ShapeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
