// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package csg

import "strconv"

type Verb int8

const (
	VerbMoveTo  Verb = 0
	VerbLineTo  Verb = 1
	VerbCubicTo Verb = 2
	VerbQuadTo  Verb = 3
	VerbClose   Verb = 4
)

var EnumNamesVerb = map[Verb]string{
	VerbMoveTo:  "MoveTo",
	VerbLineTo:  "LineTo",
	VerbCubicTo: "CubicTo",
	VerbQuadTo:  "QuadTo",
	VerbClose:   "Close",
}

var EnumValuesVerb = map[string]Verb{
	"MoveTo":  VerbMoveTo,
	"LineTo":  VerbLineTo,
	"CubicTo": VerbCubicTo,
	"QuadTo":  VerbQuadTo,
	"Close":   VerbClose,
}

func (v Verb) String() string {
	if s, ok := EnumNamesVerb[v]; ok {
		return s
	}
	return "Verb(" + strconv.FormatInt(int64(v), 10) + ")"
}
