macro(_lurpic_bool_to_text out_var value)
  if(${value})
    set(${out_var} "ON")
  else()
    set(${out_var} "OFF")
  endif()
endmacro()

set(_lurpic_summary_module_dir "${CMAKE_CURRENT_LIST_DIR}")

function(lurpic_emit_configuration_summary)
  _lurpic_bool_to_text(LURPIC_BACKEND_SOFTWARE_TEXT LURPIC_BACKEND_SOFTWARE)
  _lurpic_bool_to_text(LURPIC_BACKEND_VULKAN_TEXT LURPIC_BACKEND_VULKAN)
  _lurpic_bool_to_text(LURPIC_PLATFORM_LINUX_TEXT LURPIC_PLATFORM_LINUX)
  _lurpic_bool_to_text(LURPIC_PLATFORM_ANDROID_TEXT LURPIC_PLATFORM_ANDROID)
  _lurpic_bool_to_text(LURPIC_BUILD_TESTS_TEXT LURPIC_BUILD_TESTS)
  _lurpic_bool_to_text(LURPIC_BUILD_EXAMPLES_TEXT LURPIC_BUILD_EXAMPLES)
  _lurpic_bool_to_text(LURPIC_BUILD_BENCHMARKS_TEXT LURPIC_BUILD_BENCHMARKS)
  _lurpic_bool_to_text(LURPIC_BUILD_DOCS_TEXT LURPIC_BUILD_DOCS)
  _lurpic_bool_to_text(LURPIC_INCLUDE_TEMPLATE_THEMES_TEXT LURPIC_INCLUDE_TEMPLATE_THEMES)
  _lurpic_bool_to_text(LURPIC_ENABLE_DEBUG_VALIDATION_TEXT LURPIC_ENABLE_DEBUG_VALIDATION)
  _lurpic_bool_to_text(LURPIC_UPDATE_GOLDENS_TEXT LURPIC_UPDATE_GOLDENS)
  _lurpic_bool_to_text(LURPIC_CI_MODE_TEXT LURPIC_CI_MODE)
  _lurpic_bool_to_text(LURPIC_RELEASE_PACKAGE_TEXT LURPIC_RELEASE_PACKAGE)
  _lurpic_bool_to_text(LURPIC_HAVE_CGO_TEXT LURPIC_HAVE_CGO)
  _lurpic_bool_to_text(LURPIC_HAVE_RACE_TEXT LURPIC_HAVE_RACE)
  _lurpic_bool_to_text(LURPIC_HAVE_VULKAN_TEXT LURPIC_HAVE_VULKAN)
  _lurpic_bool_to_text(LURPIC_LINUX_PLATFORM_ENABLED_TEXT LURPIC_LINUX_PLATFORM_ENABLED)

  message(STATUS "LurpicUI configuration summary")
  message(STATUS "  Go executable: ${LURPIC_GO_EXECUTABLE}")
  message(STATUS "  Go version: ${LURPIC_GO_VERSION}")
  message(STATUS "  Go version short: ${LURPIC_GO_VERSION_SHORT}")
  message(STATUS "  Go minimum version: ${LURPIC_GO_VERSION_MINIMUM}")
  message(STATUS "  Go GOMOD: ${LURPIC_GO_GOMOD}")
  message(STATUS "  Go GOROOT: ${LURPIC_GO_GOROOT}")
  message(STATUS "  Go GOPATH: ${LURPIC_GO_GOPATH}")
  message(STATUS "  Go CGO_ENABLED: ${LURPIC_GO_CGO_ENABLED}")
  message(STATUS "  cgo available: ${LURPIC_HAVE_CGO_TEXT}")
  message(STATUS "  race detector available: ${LURPIC_HAVE_RACE_TEXT}")
  message(STATUS "  race detector hint: ${LURPIC_RACE_HINT}")
  message(STATUS "  Vulkan available: ${LURPIC_HAVE_VULKAN_TEXT}")
  message(STATUS "  Vulkan SDK root: ${LURPIC_VULKAN_SDK_ROOT}")
  message(STATUS "  Vulkan include dir: ${LURPIC_VULKAN_INCLUDE_DIR}")
  message(STATUS "  Vulkan library: ${LURPIC_VULKAN_LIBRARY}")
  message(STATUS "  Vulkan glslc: ${LURPIC_VULKAN_GLSLC}")
  message(STATUS "  Vulkan hint: ${LURPIC_VULKAN_HINT}")
  message(STATUS "  Linux platform enabled: ${LURPIC_LINUX_PLATFORM_ENABLED_TEXT}")
  message(STATUS "  backend software enabled: ${LURPIC_BACKEND_SOFTWARE_TEXT}")
  message(STATUS "  backend Vulkan enabled: ${LURPIC_BACKEND_VULKAN_TEXT}")
  message(STATUS "  software backend: ${LURPIC_BACKEND_SOFTWARE_TEXT}")
  message(STATUS "  Vulkan backend: ${LURPIC_BACKEND_VULKAN_TEXT}")
  message(STATUS "  Linux platform: ${LURPIC_PLATFORM_LINUX_TEXT}")
  message(STATUS "  Android platform: ${LURPIC_PLATFORM_ANDROID_TEXT}")
  message(STATUS "  tests: ${LURPIC_BUILD_TESTS_TEXT}")
  message(STATUS "  examples: ${LURPIC_BUILD_EXAMPLES_TEXT}")
  message(STATUS "  benchmarks: ${LURPIC_BUILD_BENCHMARKS_TEXT}")
  message(STATUS "  docs: ${LURPIC_BUILD_DOCS_TEXT}")
  message(STATUS "  template themes: ${LURPIC_INCLUDE_TEMPLATE_THEMES_TEXT}")
  message(STATUS "  debug validation: ${LURPIC_ENABLE_DEBUG_VALIDATION_TEXT}")
  message(STATUS "  golden updates: ${LURPIC_UPDATE_GOLDENS_TEXT}")
  message(STATUS "  CI mode: ${LURPIC_CI_MODE_TEXT}")
  message(STATUS "  release packaging: ${LURPIC_RELEASE_PACKAGE_TEXT}")
endfunction()

function(lurpic_add_configuration_summary_target)
  _lurpic_bool_to_text(LURPIC_BACKEND_SOFTWARE_TEXT LURPIC_BACKEND_SOFTWARE)
  _lurpic_bool_to_text(LURPIC_BACKEND_VULKAN_TEXT LURPIC_BACKEND_VULKAN)
  _lurpic_bool_to_text(LURPIC_PLATFORM_LINUX_TEXT LURPIC_PLATFORM_LINUX)
  _lurpic_bool_to_text(LURPIC_PLATFORM_ANDROID_TEXT LURPIC_PLATFORM_ANDROID)
  _lurpic_bool_to_text(LURPIC_BUILD_TESTS_TEXT LURPIC_BUILD_TESTS)
  _lurpic_bool_to_text(LURPIC_BUILD_EXAMPLES_TEXT LURPIC_BUILD_EXAMPLES)
  _lurpic_bool_to_text(LURPIC_BUILD_BENCHMARKS_TEXT LURPIC_BUILD_BENCHMARKS)
  _lurpic_bool_to_text(LURPIC_BUILD_DOCS_TEXT LURPIC_BUILD_DOCS)
  _lurpic_bool_to_text(LURPIC_INCLUDE_TEMPLATE_THEMES_TEXT LURPIC_INCLUDE_TEMPLATE_THEMES)
  _lurpic_bool_to_text(LURPIC_ENABLE_DEBUG_VALIDATION_TEXT LURPIC_ENABLE_DEBUG_VALIDATION)
  _lurpic_bool_to_text(LURPIC_UPDATE_GOLDENS_TEXT LURPIC_UPDATE_GOLDENS)
  _lurpic_bool_to_text(LURPIC_CI_MODE_TEXT LURPIC_CI_MODE)
  _lurpic_bool_to_text(LURPIC_RELEASE_PACKAGE_TEXT LURPIC_RELEASE_PACKAGE)
  _lurpic_bool_to_text(LURPIC_HAVE_CGO_TEXT LURPIC_HAVE_CGO)
  _lurpic_bool_to_text(LURPIC_HAVE_RACE_TEXT LURPIC_HAVE_RACE)
  _lurpic_bool_to_text(LURPIC_HAVE_VULKAN_TEXT LURPIC_HAVE_VULKAN)
  _lurpic_bool_to_text(LURPIC_LINUX_PLATFORM_ENABLED_TEXT LURPIC_LINUX_PLATFORM_ENABLED)

  configure_file(
    "${_lurpic_summary_module_dir}/../Scripts/ConfigureSummary.cmake.in"
    "${CMAKE_CURRENT_BINARY_DIR}/lurpic-configure-summary.cmake"
    @ONLY
  )

  add_custom_target(configure-summary
    COMMAND ${CMAKE_COMMAND} -P "${CMAKE_CURRENT_BINARY_DIR}/lurpic-configure-summary.cmake"
    VERBATIM
  )
endfunction()
